language: cpp
compiler: gcc

# Blacklist
branches:
  only:
      - master

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - doxygen

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi

cache:
  directories:
    - opencv-3.4.5/
    - opencv_contrib-3.4.5/

before_script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v
  - bash build_opencv.sh
  - cd opencv-3.4.5/build/
  - sudo make install
  - cd ../../
  # Build Darknet libs
  - cd Server/darknet/
  - make
  - cd ../../

script:
  - mkdir build
  - cd build
  - cmake ..
  - make OctoSporkClient
  - make OctoSporkServer
  - make bkgSubtraction
  - make nodeTracker
  - cd ../
  - doxygen doxyConfig

deploy:
   provider: pages
   skip_cleanup: true
   local_dir: html
   github_token: $GH_REPO_TOKEN
   on:
    branch: master


